name: Playwright Tests
on:
  workflow_call: 
    inputs:
      Env:
        required: true
        type: string
      Test:
      required: true
      type: string
    secrets:
    GIT_TOKEN:
    required: true

jobs:
  automation:
    name: Playwright-ui-automation
    run-on: ubuntu-latest
    env:
    GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
    ENV: ${{ inputs.ENV }}

    steps:
    - uses: action/checkout@v3
      id: node
      with:
        node-version: 20.9

    - name: Install Playwright and Browser
      working-directory: ./playwright-test
      run: |
        npm install
        npx playwright install

    - name: Run UI tests
        working-directory: ./playwright-test
        run: npm run ${{ inputs.TEST }}

    - name: Generate reports
        if: always()
        working-directory: ./playwright-test
        run: npm run report

  - name: Publishing Results
      if: always()
      working-directory: actions/upload-artifacts@v3
      with:
       name: test-report
       path: ./playwright/reports
